### ISSUE TITLE
Configure LSP with clangd

### ISSUE THREAD

**Issue by pathakraul** [avegancafe/VimStudio#3]
Hi, tried vimstudio, looks good. 
I keep getting message **install homebrew in order to use LSPs** but i have a ubuntu machine. 

I don't know fennel lang. Installed clangd lsp but couldn't configure.

**Comment by avegancafe** [comment]
Hey @pathakraul ! Ahh, you can customize the entries in `lspconfig.fnl`, if you don't want some of those you can remove them. And if you want others, you just have to instantiate it with its LSP name listed in `:Mason`

**Comment by pathakraul** [comment]
Thanks, I am able to make it work now.
